import { RouteInfo } from "./horizontal-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "home",
    title: "Home",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      
    ],
  },
  {
    path: "",
    title: "Bras",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      {
        path: "bras-style/seamless",
        title: "Seamless",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/strapless-bras",
        title: "Beginners Bra/Camisole Bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/T-shirt-bras",
        title: "T-Shirt Bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/minimizer-Bras",
        title: "Minimizer Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/pushupbra",
        title: "Push up Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/Plunge-bra",
        title: "Seamless",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/bandeaubra",
        title: "Bandeau bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/Balconette",
        title: "Balconette Bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/straplessbra",
        title: "Strapless Bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/nursingbra",
        title: "Nursing Bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/cottonbra",
        title: "Cotton Bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/MastectomyBra",
        title: "Mastectomy Bra",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "bras-style/bridalsets",
        title: "Bridal Sets",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
  
    ],
  },
  
  {
    path: "",
    title: "Panties",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      {
        path: "panties-style/boyshorts",
        title: "Hipster",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
   
      {
        path: "panties-style/brazilian-panties",
        title: "Brief",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "panties-style/cheekies",
        title: "Lace",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      // {
      //   path: "",
      //   title: "Boy Shorts",
      //   icon: "",
      //   class: "",
      //   ddclass: "",
      //   extralink: false,
      //   submenu: [],
      // },
      // {
      //   path: "panties-style/garters",
      //   title: "Bikinis",
      //   icon: "",
      //   class: "",
      //   ddclass: "",
      //   extralink: false,
      //   submenu: [],
      // },
      {
        path: "panties-style/hiphuggers",
        title: "Boy Shorts",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      // {
      //   path: "panties-style/high-waist",
      //   title: "High-Waist & High-Leg",
      //   icon: "",
      //   class: "",
      //   ddclass: "",
      //   extralink: false,
      //   submenu: [],
      // },
     
      
      // {
      //   path: "panties-style/shapewear",
      //   title: "Shapewear",
      //   icon: "",
      //   class: "",
      //   ddclass: "",
      //   extralink: false,
      //   submenu: [],
      // },
      // {
      //   path: "panties-style/thongs-v-strings",
      //   title: "Thongs & V-Strings",
      //   icon: "",
      //   class: "",
      //   ddclass: "",
      //   extralink: false,
      //   submenu: [],
      // },
      
    ],
  }, 
  // {
  //   path: "essentials",
  //   title: "Essentials",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
     
  //   ],
  // },
  // {
  //   path: "lakeproof",
  //   title: "Leakproof",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
      
  //   ],
  // }, 
 
  {
    path: "activewear",
    title: "Active Wear",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      
    ],
  }, 
  // {
  //   path: "swimwear",
  //   title: "Swim Wear",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
      
  //   ],
  // }, 
  // {
  //   path: "",
  //   title: "Special Needs",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
      
  //   ],
  // }, 
  // {
  //   path: "product-components/cart",
  //   title: "cart",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
      
  //   ],
  // }, 
];
