import { RouteInfo } from "./horizontal-sidebar.metadata";

export const ROUTES: RouteInfo[] = [
  {
    path: "home",
    title: "Home",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      
    ],
  },
  {
    path: "bras",
    title: "Bras",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      {
        path: "bras-style/pushupbras",
        title: "Push-Up Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Strapless Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Full Coverage Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Sports Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Wireless Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Lightly Lined Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "T-Shirt Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Unlined Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Bralettes",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Corset Tops",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Balconette Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "DD+ Bras",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
    ],
  },
  
  {
    path: "panties",
    title: "Panties",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      {
        path: "product-components/brasview",
        title: "Thongs & V-Strings",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Brazilian Panties",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Cheekies & Cheekinis",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Bikinis & Briefs",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Hiphuggers",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "High-Waist & High-Leg",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Boyshorts",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Garters & Hosiery",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Shapewear",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
      {
        path: "",
        title: "Adaptive Bras & Panties",
        icon: "",
        class: "",
        ddclass: "",
        extralink: false,
        submenu: [],
      },
     
      
    ],
  }, 
  {
    path: "essentials",
    title: "Essentials",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
     
    ],
  },
  {
    path: "lakeproof",
    title: "Leakproof",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      
    ],
  }, 
 
  {
    path: "activewear",
    title: "Active Wear",
    icon: "",
    class: "",
    ddclass: "",
    extralink: false,
    submenu: [
      
    ],
  }, 
  // {
  //   path: "swimwear",
  //   title: "Swim Wear",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
      
  //   ],
  // }, 
  // {
  //   path: "",
  //   title: "Special Needs",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
      
  //   ],
  // }, 
  // {
  //   path: "product-components/cart",
  //   title: "cart",
  //   icon: "",
  //   class: "",
  //   ddclass: "",
  //   extralink: false,
  //   submenu: [
      
  //   ],
  // }, 
];
